
name: CI Workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set Up NodeJS v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Analyze Code using ESLint
      run: npm run lint
    
    - name: Build
      run: npm run build

